### ISSUE TITLE
Attribute Error: module 'pyfes' has no attribute 'load_config'

### ISSUE THREAD

**Issue by AryanAdhau** [CNES/aviso-fes#34]
Hii
I am working with CoastSat 3.1 for tidal corrections (https://github.com/kvos/CoastSat), and downloaded the updated fe2022b files from Aviso. However, I am getting the error while setting it up (while testing). The error is "Attribute Error: module 'pyfes' has no attribute 'load_config'". CoastSat requires Python 3.8 version. Is it the problem because of that? Could you help me with this.

```python 
import pyfes
<< >>> import pyfes
>>> import os
>>> filepath = os.path.join('D:', os.sep, 'Thesis', 'tide_model', 'fes2022b', 'fes2022.yaml')
>>> config = os.path.join(filepath, 'fes2022.yaml')
>>> handlers = pyfes.load_config(config)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyfes' has no attribute 'load_config'>>
```
I have kept my Aviso fes tide dataset in D drive while my CoastSat conda from where I intend to run pyfes is in C drive. Can this be the reason?

Thanks
